version: 2
jobs:
  deploy_trunk:
      machine:
        docker_layer_caching: true
      steps:
        - checkout
        - run:
            command: |
              set -x
              export VERSION=$CIRCLE_BUILD_NUM
              docker -v
              docker login --username $DOCKER_USER --password $DOCKER_PASS

              export IMAGE_NAME=convolab/line-flex-editor
              echo "Start building $IMAGE_NAME"
              docker build -t $IMAGE_NAME:$VERSION .
              docker push $IMAGE_NAME:$VERSION
              docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
              docker push $IMAGE_NAME:latest

  build_app:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          command: |
            set -x
            export VERSION=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            docker login --username $DOCKER_USER --password $DOCKER_PASS
            export IMAGE_NAME=convolab/line-flex-editor
            echo "Start building $IMAGE_NAME"
            docker build -t $IMAGE_NAME:$VERSION .
            docker push $IMAGE_NAME:$VERSION
            docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:$CIRCLE_BRANCH-latest
            docker push $IMAGE_NAME:$CIRCLE_BRANCH-latest

  build_trunk:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          command: |
            set -x
            export VERSION=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            docker -v
            docker login --username $DOCKER_USER --password $DOCKER_PASS

            export IMAGE_NAME=convolab/line-flex-editor
            echo "Start building $IMAGE_NAME"
            docker build -t $IMAGE_NAME:$VERSION .
            docker push $IMAGE_NAME:$VERSION
            docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:$CIRCLE_BRANCH-latest
            docker push $IMAGE_NAME:$CIRCLE_BRANCH-latest
workflows:
  version: 2
  build_app:
      jobs:
        - build_app:
            filters:
              tags:
                ignore: /^rebuild.*/
              branches:
                ignore:
                  - alpha
                  - master
  build_trunk:
      jobs:
        - build_trunk:
            filters:
              branches:
                only:
                  - alpha
  deploy_trunk:
      jobs:
        - deploy_trunk:
            filters:
              branches:
                only:
                  - master